status = warn
name = SMActiveRuleLogger

appender.console.type = File
appender.console.name = STDOUT
appender.console.fileName = /proc/1/fd/1
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%d{ISO8601}] %-5p %c{1} - %m%n

logger.mylogger.name = com.broadcom.example
logger.mylogger.level = debug
logger.mylogger.additivity = false
logger.mylogger.appenderRef.stdout.ref = STDOUT

rootLogger.level = info
rootLogger.appenderRef.stdout.ref = STDOUT
